### ISSUE TITLE
Suggested Updates for Mobile Foundation: Getting Started Tutorial

### ISSUE THREAD

**Issue by danielchen-AppDev** [ibm-cloud-docs/mobilefoundation#6]
There are several areas in the Getting Started tutorial that lack the details required to complete it. Additionally, a couple of the steps have misleading or extraneous information that should be changed or removed from the tutorial entirely. Each step is briefly listed in the document, along with suggested improvements for the documentation. If this tutorial could be updated to match the following document, that would be much appreciated.

[Mobile Foundation Tutorial_ Updates to Documentation.docx](https://github.com/IBM-Bluemix-Docs/mobilefoundation/files/3462648/Mobile.Foundation.Tutorial_.Updates.to.Documentation.docx)

Thanks,
Daniel Chen
IBM Cloud - ACS AppDev

**Comment by hisubram** [comment]
Comments taken care. Thanks for your suggestions and comments.
