### ISSUE TITLE
Xamarin/Windows Pre-empt Login does not return data

### ISSUE THREAD

**Issue by CarlosMobileAppDeveloper** [ibm-cloud-docs/mobilefoundation#7]
Hi,

I am currently using the IBM.MobileFirstPlatformFoundation SDK/Nuget package for a Xamarin app, but having an issue with getting response data from the preemtive Login method.

_WorklightResponse response = await Worklight.WorklightClient.CreateInstance().AuthorizationManager.**Login**(String securityCheckName, JObject credentials);_

When successfully using the preemptive login there is no data returned. The WorklightResponse ResponseText & ResponseJSON are both null, but Success is True. 
However, I can see in Fiddler that the JSON data about the User is being sent back to the client, but it appears the SDK is not handling this correctly and not returning it as part of the WorklightResponse?

https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/authentication-and-security/user-authentication/windows-8-10/

https://github.com/MobileFirst-Platform-Developer-Center/PreemptiveLoginWin10/blob/release80/PreemptiveLoginWin10/PreemptiveLoginChallengeHandler.cs

**Comment by hisubram** [comment]
Thanks for reporting the issue. We will look into it and respond.

**Comment by manjunath143** [comment]
The Login API success call's WorklightResponse having ResponseText & ResponseJSON as null, is as per design. The payload that is seen in the Fiddler is for internal consumption by the MF SDK. 

Same has been already clarified to the customer via mail.

**Comment by sreelathasankaranarayanan** [comment]
Closing this issue based on @manjunath143 comment above.
